Repository algoives/TestBankApp, pull requests merged in 2022-03, with the labels that each got.

#7 Work in dbrelationships
  TestBankApp/Base.lproj/Main.storyboard
Labels: 1

#8 Working on issue #1
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/admin.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/admin.xcuserdatad/xcschemes/xcschememanagement.plist
  TestBankApp/Base.lproj/Main.storyboard
Labels: 1

#40 Logic for issue #39
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/admin.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Utilities/Validation.swift
  TestBankApp/ViewControllers/RegistrationViewController.swift
  TestBankApp/ViewControllers/ViewController.swift
Labels: Design

#47 Integrate Database #45
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/Model/QuizzAppDB.db
  TestBankApp/ViewControllers/RegistrationViewController.swift
Labels: Build

#48 Build queriesqueries
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/algoives.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  TestBankApp/Model/DBHelper.swift
  TestBankApp/Model/Quizz.swift
  TestBankApp/Model/User.swift
  TestBankApp/ViewControllers/RegistrationViewController.swift
Labels: Build

#50 Work on quizz selction view
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Assets.xcassets/IOS.imageset/Contents.json
  TestBankApp/Assets.xcassets/IOS.imageset/iosLogo.jpeg
  TestBankApp/Assets.xcassets/Swift.imageset/Contents.json
  TestBankApp/Assets.xcassets/Swift.imageset/swiftlogo.jpeg
  TestBankApp/Assets.xcassets/X-code.imageset/Contents.json
  TestBankApp/Assets.xcassets/X-code.imageset/xcodeLogo.jpeg
  TestBankApp/Assets.xcassets/apple.imageset/Contents.json
  TestBankApp/Assets.xcassets/apple.imageset/apple.jpeg
  TestBankApp/Assets.xcassets/swiftLogo2.imageset/Contents.json
  TestBankApp/Assets.xcassets/swiftLogo2.imageset/swiftLogo2.png
  TestBankApp/Assets.xcassets/switlogo3.imageset/Contents.json
  TestBankApp/Assets.xcassets/switlogo3.imageset/switlogo3.png
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/ViewControllers/quizzSelection/QuizzCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzTechSelectionViewController.swift
Labels: Build

#54 Fixed Admin Screen Logic and added new Images and UI to login screens…
  .DS_Store
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/admin.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/admin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  TestBankApp/.DS_Store
  TestBankApp/Assets.xcassets/TestBankLogo.imageset/Contents.json
  TestBankApp/Assets.xcassets/TestBankLogo.imageset/TestBankLogo.jpeg
  TestBankApp/Assets.xcassets/TestMeLogoBanner.imageset/Contents.json
  TestBankApp/Assets.xcassets/TestMeLogoBanner.imageset/TestMeLogoBanner.jpeg
  TestBankApp/Base.lproj/LaunchScreen.storyboard
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/Utilities/Utilities.swift
  TestBankApp/ViewControllers/AdminLoginViewController.swift
  TestBankApp/ViewControllers/HomeViewController.swift
  TestBankApp/ViewControllers/LoginViewController.swift
  TestBankApp/ViewControllers/RegistrationViewController.swift
Labels: Design, Build

#55 Got the User Login working completely. #52
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/admin.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/ViewControllers/AdminLoginViewController.swift
  TestBankApp/ViewControllers/LoginViewController.swift
Labels: Build

#56 Work on selectio quizz Business logic
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/algoives.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/User.swift
  TestBankApp/ViewControllers/quizzSelection/IOSCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzTechSelectionViewController.swift
  TestBankApp/ViewControllers/quizzSelection/SelectionQuizzViewController.swift
  TestBankApp/ViewControllers/quizzSelection/SwiftCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/XcodeCollectionViewCell.swift
Labels: Design, Build

#58 Add Quizz Slection logic #49
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/algoives.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/ViewControllers/quizzSelection/QuizIOSCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzSwiftCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzXcodeCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/SelctionQuizzViewController.swift
Labels: Design, Build

#63 Add logic for quizz atempt
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/Model/GlobalVariables.swift
  TestBankApp/Model/Question.swift
  TestBankApp/Model/Quizz.swift
  TestBankApp/Model/User.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzSwiftCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzViewController.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzXcodeCollectionViewCell.swift
  TestBankApp/ViewControllers/quizzSelection/SelctionQuizzViewController.swift
Labels: Build

#68 Work on quizz attempt
  TestBankApp.xcodeproj/project.pbxproj
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/Model/DBHelper.swift
  TestBankApp/Model/GlobalVariables.swift
  TestBankApp/ViewControllers/LoginViewController.swift
  TestBankApp/ViewControllers/ResultViewController.swift
  TestBankApp/ViewControllers/quizzSelection/QuizzViewController.swift
  TestBankApp/ViewControllers/quizzSelection/SelctionQuizzViewController.swift
Labels: Build

#82 Add timer to Quizz view
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/ViewControllers/quizzSelection/QuizzViewController.swift
Labels: Build

#89 ADD table of rankings to rankings view
  TestBankApp.xcodeproj/project.xcworkspace/xcuserdata/algoives.xcuserdatad/UserInterfaceState.xcuserstate
  TestBankApp.xcodeproj/xcuserdata/algoives.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  TestBankApp/Base.lproj/Main.storyboard
  TestBankApp/ViewControllers/quizzSelection/QuizzTechSelectionViewController.swift
Labels: Build
